#######################################################
# 
# Admin.py
# Python implementation of the Class Admin
# Generated by Enterprise Architect
# Created on:      13-mar.-2020 7:15:36 a. m.
# Original author: Niko
# 
#######################################################


class Admin:
    def ApovarUss(DNI):
        pass

    def CrearContenido():
        pass

    def ModificarContenido():
        pass