#######################################################
# 
# Contenido.py
# Python implementation of the Class Contenido
# Generated by Enterprise Architect
# Created on:      13-mar.-2020 7:15:44 a. m.
# Original author: xlOnly
# 
#######################################################


class Contenido:
    def getIntereses():
        pass

    def getMultimedia():
        pass

    def getNoticias():
        pass

    def setIntereses(interes):
        pass

    def setMultimedia(multimedia):
        pass

    def setNoticias(noticia):
        pass