#######################################################
# 
# Egresados.py
# Python implementation of the Class Egresados
# Generated by Enterprise Architect
# Created on:      13-mar.-2020 7:15:46 a. m.
# Original author: xlOnly
# 
#######################################################


class Egresados:
    def BuscarEgresado(Nombre):
        pass

    def Chatear(Mensaje):
        pass

    def CrearUss(DNI, Edad, Nombre, Apellido, Telefono, Correo, Contraseña, Pais, Genero, Interes, ManejoDatos):
        pass

    def Mensajes():
        pass

    def ModificarUss(DNI, Edad, Nombre, Apellido, Telefono, Correo, Contraseña, Pais, Genero, Interes, ManejoDatos):
        pass