#######################################################
# 
# Inicio_Sesion.py
# Python implementation of the Class Inicio_Sesion
# Generated by Enterprise Architect
# Created on:      13-mar.-2020 7:16:20 a. m.
# Original author: Estudiante
# 
#######################################################


class Inicio_Sesion:
    def CambiarClave(Clave):
        pass

    def __EncriptarPass(clave):
        pass

    def getValidadcion(correo, clave):
        pass

    def Solicitud():
        pass