#######################################################
# 
# Persona.py
# Python implementation of the Class Persona
# Generated by Enterprise Architect
# Created on:      13-mar.-2020 7:16:25 a. m.
# Original author: xlOnly
# 
#######################################################


class Persona:
    def getCiudad():
        pass

    def getCorreo():
        pass

    def getDireccion():
        pass

    def getDNI():
        pass

    def getNombre():
        pass

    def getTelefono():
        pass

    def setCiudad(ciudad):
        pass

    def setCorreo(correo):
        pass

    def setDireccion(direccion):
        pass

    def setDNI(DNI):
        pass

    def setNombre(Nombre, Apellidp):
        pass

    def setTelefono(telefono):
        pass