#######################################################
# 
# SuperUsser.py
# Python implementation of the Class SuperUsser
# Generated by Enterprise Architect
# Created on:      13-mar.-2020 7:16:28 a. m.
# Original author: xlOnly
# 
#######################################################


class SuperUsser:
    def ConsultarAdmin():
        pass

    def CrearAdmin(DNi, Nombre, Apellido, Direccion, Ciudad, Correo, Telefono):
        pass

    def DesactivarAdmin(DNI):
        pass

    def ModificarAdmin():
        pass

    def SesionActiva(DNI):
        pass