#######################################################
# 
# Encriptacion.py
# Python implementation of the Class Encriptacion
# Generated by Enterprise Architect
# Created on:      13-mar.-2020 7:16:20 a. m.
# Original author: xlOnly
# 
#######################################################


class Encriptacion:
    def CambiarClave(Clave):
        pass

    def EncriptarClave(Clave):
        pass